<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>info argopuro</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>26b3feda-5146-4e9e-9950-e5a0c17a9045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dbaaadb9-5f7e-469b-8d25-2d2dac108001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Gunung Argopuro atau disebut juga “Argopura” adalah gunung api yang terletak di Jawa Timur tepatnya di perbatasan kabupaten Probolinggo, Situbondo dan Bondowoso. Argopuro memiliki arti “Argo=Gunung” dan “Puro=pura” sama dengan “Pura di atas gunung. Gunung ini sudah tidak aktif lagi. Gunung Argopuro memiliki ketinggian 3.088 mdpl.
     Gunung Argopuro masuk dalam kawaasan Pegunungan Iyang di Jawa Timur. Secara geografis gunung Argopuro berdiri di antara kedua gunung yang memiliki peringkat khusus di Indonesia yakni Gunung Semeru (puncak tertinggi di Jawa) dan Gunung Raung (trek tersulit). Jika Semeru dan Raung ber-peringkat maka Argopuro juga demikian adanya, Gunung Argopuro berperingkat sebagai gunung dengan jalur pendakian terpanjang di Jawa.</value>
      <webElementGuid>a3a048a4-d082-4351-aa9a-40885abc664f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>com.wahidari.pendaki:id/detail_gunung</value>
      <webElementGuid>512c23ac-8c27-4b53-a683-6252523cc20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.wahidari.pendaki</value>
      <webElementGuid>c3848329-9a87-4a67-ab4a-817e592e0227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e5c9fea-b543-43e9-92f0-64d174d63fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da143178-e4ed-43a5-bc3c-4916ba7f1f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6969da7-de74-4716-ac4f-81c289e2cd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6613b4d9-1fbc-43f4-ac9d-a2086b8db843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3d3eba2-2502-4740-a7cb-d03c8c6d2763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0474910-f0cb-4ff2-a635-b51182569999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ece289f9-afa3-4723-93c7-a5c5ae93a478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>63d0a982-6ce4-498a-906d-534f0c28ad1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cfefb438-e902-480a-9efc-7604c67d0fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>885874d0-aa39-42c1-8f50-54ce1586c298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>c7d7708c-b170-4f80-8e19-8a615e5a3b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>601</value>
      <webElementGuid>a3e857b6-4dba-4311-903d-4e51e51440cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>672</value>
      <webElementGuid>2451fc8c-f19c-41f6-9657-cb8c88148286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>727</value>
      <webElementGuid>307f9cf6-add0-47fb-bff5-8bccc49c5810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[24,601][696,1328]</value>
      <webElementGuid>f788eb8f-e5a4-43e4-9703-db7c5082a2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73b69b0f-c146-4e71-afb9-a0e258d4d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.TextView[2]</value>
      <webElementGuid>56c519d6-21e1-4625-ba7a-8272db668caf</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = '     Gunung Argopuro atau disebut juga “Argopura” adalah gunung api yang terletak di Jawa Timur tepatnya di perbatasan kabupaten Probolinggo, Situbondo dan Bondowoso. Argopuro memiliki arti “Argo=Gunung” dan “Puro=pura” sama dengan “Pura di atas gunung. Gunung ini sudah tidak aktif lagi. Gunung Argopuro memiliki ketinggian 3.088 mdpl.
     Gunung Argopuro masuk dalam kawaasan Pegunungan Iyang di Jawa Timur. Secara geografis gunung Argopuro berdiri di antara kedua gunung yang memiliki peringkat khusus di Indonesia yakni Gunung Semeru (puncak tertinggi di Jawa) dan Gunung Raung (trek tersulit). Jika Semeru dan Raung ber-peringkat maka Argopuro juga demikian adanya, Gunung Argopuro berperingkat sebagai gunung dengan jalur pendakian terpanjang di Jawa.' or . = '     Gunung Argopuro atau disebut juga “Argopura” adalah gunung api yang terletak di Jawa Timur tepatnya di perbatasan kabupaten Probolinggo, Situbondo dan Bondowoso. Argopuro memiliki arti “Argo=Gunung” dan “Puro=pura” sama dengan “Pura di atas gunung. Gunung ini sudah tidak aktif lagi. Gunung Argopuro memiliki ketinggian 3.088 mdpl.
     Gunung Argopuro masuk dalam kawaasan Pegunungan Iyang di Jawa Timur. Secara geografis gunung Argopuro berdiri di antara kedua gunung yang memiliki peringkat khusus di Indonesia yakni Gunung Semeru (puncak tertinggi di Jawa) dan Gunung Raung (trek tersulit). Jika Semeru dan Raung ber-peringkat maka Argopuro juga demikian adanya, Gunung Argopuro berperingkat sebagai gunung dengan jalur pendakian terpanjang di Jawa.') and @resource-id = 'com.wahidari.pendaki:id/detail_gunung']</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
